// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: heya/erc20/v1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryBalanceOfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBalanceOfRequest) Reset() {
	*x = QueryBalanceOfRequest{}
	mi := &file_heya_erc20_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBalanceOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBalanceOfRequest) ProtoMessage() {}

func (x *QueryBalanceOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBalanceOfRequest.ProtoReflect.Descriptor instead.
func (*QueryBalanceOfRequest) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryBalanceOfRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *QueryBalanceOfRequest) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type QueryBalanceOfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBalanceOfResponse) Reset() {
	*x = QueryBalanceOfResponse{}
	mi := &file_heya_erc20_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBalanceOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBalanceOfResponse) ProtoMessage() {}

func (x *QueryBalanceOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBalanceOfResponse.ProtoReflect.Descriptor instead.
func (*QueryBalanceOfResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryBalanceOfResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type QueryAllowanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender       string                 `protobuf:"bytes,2,opt,name=spender,proto3" json:"spender,omitempty"`
	Denom         string                 `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllowanceRequest) Reset() {
	*x = QueryAllowanceRequest{}
	mi := &file_heya_erc20_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllowanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllowanceRequest) ProtoMessage() {}

func (x *QueryAllowanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllowanceRequest.ProtoReflect.Descriptor instead.
func (*QueryAllowanceRequest) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryAllowanceRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *QueryAllowanceRequest) GetSpender() string {
	if x != nil {
		return x.Spender
	}
	return ""
}

func (x *QueryAllowanceRequest) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type QueryAllowanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllowanceResponse) Reset() {
	*x = QueryAllowanceResponse{}
	mi := &file_heya_erc20_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllowanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllowanceResponse) ProtoMessage() {}

func (x *QueryAllowanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllowanceResponse.ProtoReflect.Descriptor instead.
func (*QueryAllowanceResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAllowanceResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type QueryTotalSupplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTotalSupplyRequest) Reset() {
	*x = QueryTotalSupplyRequest{}
	mi := &file_heya_erc20_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTotalSupplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTotalSupplyRequest) ProtoMessage() {}

func (x *QueryTotalSupplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTotalSupplyRequest.ProtoReflect.Descriptor instead.
func (*QueryTotalSupplyRequest) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryTotalSupplyRequest) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type QueryTotalSupplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTotalSupplyResponse) Reset() {
	*x = QueryTotalSupplyResponse{}
	mi := &file_heya_erc20_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTotalSupplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTotalSupplyResponse) ProtoMessage() {}

func (x *QueryTotalSupplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTotalSupplyResponse.ProtoReflect.Descriptor instead.
func (*QueryTotalSupplyResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryTotalSupplyResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_heya_erc20_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_query_proto_rawDescGZIP(), []int{6}
}

type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_heya_erc20_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryParamsResponse) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

var File_heya_erc20_v1_query_proto protoreflect.FileDescriptor

const file_heya_erc20_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x19heya/erc20/v1/query.proto\x12\rheya.erc20.v1\"C\n" +
	"\x15QueryBalanceOfRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\"0\n" +
	"\x16QueryBalanceOfResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\"]\n" +
	"\x15QueryAllowanceRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x18\n" +
	"\aspender\x18\x02 \x01(\tR\aspender\x12\x14\n" +
	"\x05denom\x18\x03 \x01(\tR\x05denom\"0\n" +
	"\x16QueryAllowanceResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\"/\n" +
	"\x17QueryTotalSupplyRequest\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\"2\n" +
	"\x18QueryTotalSupplyResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\"\x14\n" +
	"\x12QueryParamsRequest\"3\n" +
	"\x13QueryParamsResponse\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority2\xec\x02\n" +
	"\x05Query\x12X\n" +
	"\tBalanceOf\x12$.heya.erc20.v1.QueryBalanceOfRequest\x1a%.heya.erc20.v1.QueryBalanceOfResponse\x12X\n" +
	"\tAllowance\x12$.heya.erc20.v1.QueryAllowanceRequest\x1a%.heya.erc20.v1.QueryAllowanceResponse\x12^\n" +
	"\vTotalSupply\x12&.heya.erc20.v1.QueryTotalSupplyRequest\x1a'.heya.erc20.v1.QueryTotalSupplyResponse\x12O\n" +
	"\x06Params\x12!.heya.erc20.v1.QueryParamsRequest\x1a\".heya.erc20.v1.QueryParamsResponseB\x14Z\x12heya/x/erc20/typesb\x06proto3"

var (
	file_heya_erc20_v1_query_proto_rawDescOnce sync.Once
	file_heya_erc20_v1_query_proto_rawDescData []byte
)

func file_heya_erc20_v1_query_proto_rawDescGZIP() []byte {
	file_heya_erc20_v1_query_proto_rawDescOnce.Do(func() {
		file_heya_erc20_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heya_erc20_v1_query_proto_rawDesc), len(file_heya_erc20_v1_query_proto_rawDesc)))
	})
	return file_heya_erc20_v1_query_proto_rawDescData
}

var file_heya_erc20_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_heya_erc20_v1_query_proto_goTypes = []any{
	(*QueryBalanceOfRequest)(nil),    // 0: heya.erc20.v1.QueryBalanceOfRequest
	(*QueryBalanceOfResponse)(nil),   // 1: heya.erc20.v1.QueryBalanceOfResponse
	(*QueryAllowanceRequest)(nil),    // 2: heya.erc20.v1.QueryAllowanceRequest
	(*QueryAllowanceResponse)(nil),   // 3: heya.erc20.v1.QueryAllowanceResponse
	(*QueryTotalSupplyRequest)(nil),  // 4: heya.erc20.v1.QueryTotalSupplyRequest
	(*QueryTotalSupplyResponse)(nil), // 5: heya.erc20.v1.QueryTotalSupplyResponse
	(*QueryParamsRequest)(nil),       // 6: heya.erc20.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),      // 7: heya.erc20.v1.QueryParamsResponse
}
var file_heya_erc20_v1_query_proto_depIdxs = []int32{
	0, // 0: heya.erc20.v1.Query.BalanceOf:input_type -> heya.erc20.v1.QueryBalanceOfRequest
	2, // 1: heya.erc20.v1.Query.Allowance:input_type -> heya.erc20.v1.QueryAllowanceRequest
	4, // 2: heya.erc20.v1.Query.TotalSupply:input_type -> heya.erc20.v1.QueryTotalSupplyRequest
	6, // 3: heya.erc20.v1.Query.Params:input_type -> heya.erc20.v1.QueryParamsRequest
	1, // 4: heya.erc20.v1.Query.BalanceOf:output_type -> heya.erc20.v1.QueryBalanceOfResponse
	3, // 5: heya.erc20.v1.Query.Allowance:output_type -> heya.erc20.v1.QueryAllowanceResponse
	5, // 6: heya.erc20.v1.Query.TotalSupply:output_type -> heya.erc20.v1.QueryTotalSupplyResponse
	7, // 7: heya.erc20.v1.Query.Params:output_type -> heya.erc20.v1.QueryParamsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heya_erc20_v1_query_proto_init() }
func file_heya_erc20_v1_query_proto_init() {
	if File_heya_erc20_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heya_erc20_v1_query_proto_rawDesc), len(file_heya_erc20_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heya_erc20_v1_query_proto_goTypes,
		DependencyIndexes: file_heya_erc20_v1_query_proto_depIdxs,
		MessageInfos:      file_heya_erc20_v1_query_proto_msgTypes,
	}.Build()
	File_heya_erc20_v1_query_proto = out.File
	file_heya_erc20_v1_query_proto_goTypes = nil
	file_heya_erc20_v1_query_proto_depIdxs = nil
}
