// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: heya/erc20/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTransfer) Reset() {
	*x = MsgTransfer{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTransfer) ProtoMessage() {}

func (x *MsgTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTransfer.ProtoReflect.Descriptor instead.
func (*MsgTransfer) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgTransfer) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgTransfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MsgTransfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTransferResponse) Reset() {
	*x = MsgTransferResponse{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTransferResponse) ProtoMessage() {}

func (x *MsgTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTransferResponse.ProtoReflect.Descriptor instead.
func (*MsgTransferResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{1}
}

type MsgApprove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender       string                 `protobuf:"bytes,2,opt,name=spender,proto3" json:"spender,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgApprove) Reset() {
	*x = MsgApprove{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgApprove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgApprove) ProtoMessage() {}

func (x *MsgApprove) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgApprove.ProtoReflect.Descriptor instead.
func (*MsgApprove) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgApprove) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgApprove) GetSpender() string {
	if x != nil {
		return x.Spender
	}
	return ""
}

func (x *MsgApprove) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgApproveResponse) Reset() {
	*x = MsgApproveResponse{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgApproveResponse) ProtoMessage() {}

func (x *MsgApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgApproveResponse.ProtoReflect.Descriptor instead.
func (*MsgApproveResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgTransferFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        string                 `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTransferFrom) Reset() {
	*x = MsgTransferFrom{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTransferFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTransferFrom) ProtoMessage() {}

func (x *MsgTransferFrom) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTransferFrom.ProtoReflect.Descriptor instead.
func (*MsgTransferFrom) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgTransferFrom) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *MsgTransferFrom) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MsgTransferFrom) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MsgTransferFrom) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgTransferFromResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTransferFromResponse) Reset() {
	*x = MsgTransferFromResponse{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTransferFromResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTransferFromResponse) ProtoMessage() {}

func (x *MsgTransferFromResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTransferFromResponse.ProtoReflect.Descriptor instead.
func (*MsgTransferFromResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{5}
}

type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	NewAuthority  string                 `protobuf:"bytes,2,opt,name=new_authority,json=newAuthority,proto3" json:"new_authority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetNewAuthority() string {
	if x != nil {
		return x.NewAuthority
	}
	return ""
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{7}
}

type MsgIncreaseAllowance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender       string                 `protobuf:"bytes,2,opt,name=spender,proto3" json:"spender,omitempty"`
	Denom         string                 `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgIncreaseAllowance) Reset() {
	*x = MsgIncreaseAllowance{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgIncreaseAllowance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgIncreaseAllowance) ProtoMessage() {}

func (x *MsgIncreaseAllowance) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgIncreaseAllowance.ProtoReflect.Descriptor instead.
func (*MsgIncreaseAllowance) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgIncreaseAllowance) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgIncreaseAllowance) GetSpender() string {
	if x != nil {
		return x.Spender
	}
	return ""
}

func (x *MsgIncreaseAllowance) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgIncreaseAllowance) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgIncreaseAllowanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgIncreaseAllowanceResponse) Reset() {
	*x = MsgIncreaseAllowanceResponse{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgIncreaseAllowanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgIncreaseAllowanceResponse) ProtoMessage() {}

func (x *MsgIncreaseAllowanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgIncreaseAllowanceResponse.ProtoReflect.Descriptor instead.
func (*MsgIncreaseAllowanceResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{9}
}

type MsgDecreaseAllowance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Spender       string                 `protobuf:"bytes,2,opt,name=spender,proto3" json:"spender,omitempty"`
	Denom         string                 `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDecreaseAllowance) Reset() {
	*x = MsgDecreaseAllowance{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDecreaseAllowance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDecreaseAllowance) ProtoMessage() {}

func (x *MsgDecreaseAllowance) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDecreaseAllowance.ProtoReflect.Descriptor instead.
func (*MsgDecreaseAllowance) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgDecreaseAllowance) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MsgDecreaseAllowance) GetSpender() string {
	if x != nil {
		return x.Spender
	}
	return ""
}

func (x *MsgDecreaseAllowance) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgDecreaseAllowance) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgDecreaseAllowanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDecreaseAllowanceResponse) Reset() {
	*x = MsgDecreaseAllowanceResponse{}
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDecreaseAllowanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDecreaseAllowanceResponse) ProtoMessage() {}

func (x *MsgDecreaseAllowanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_erc20_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDecreaseAllowanceResponse.ProtoReflect.Descriptor instead.
func (*MsgDecreaseAllowanceResponse) Descriptor() ([]byte, []int) {
	return file_heya_erc20_v1_tx_proto_rawDescGZIP(), []int{11}
}

var File_heya_erc20_v1_tx_proto protoreflect.FileDescriptor

const file_heya_erc20_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x16heya/erc20/v1/tx.proto\x12\rheya.erc20.v1\x1a\x17cosmos/msg/v1/msg.proto\"Z\n" +
	"\vMsgTransfer\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount:\v\x82\xe7\xb0*\x06sender\"\x15\n" +
	"\x13MsgTransferResponse\"`\n" +
	"\n" +
	"MsgApprove\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x18\n" +
	"\aspender\x18\x02 \x01(\tR\aspender\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount:\n" +
	"\x82\xe7\xb0*\x05owner\"\x14\n" +
	"\x12MsgApproveResponse\"r\n" +
	"\x0fMsgTransferFrom\x12\x16\n" +
	"\x06caller\x18\x01 \x01(\tR\x06caller\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount:\v\x82\xe7\xb0*\x06caller\"\x19\n" +
	"\x17MsgTransferFromResponse\"d\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12#\n" +
	"\rnew_authority\x18\x02 \x01(\tR\fnewAuthority:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse\"\x80\x01\n" +
	"\x14MsgIncreaseAllowance\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x18\n" +
	"\aspender\x18\x02 \x01(\tR\aspender\x12\x14\n" +
	"\x05denom\x18\x03 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount:\n" +
	"\x82\xe7\xb0*\x05owner\"\x1e\n" +
	"\x1cMsgIncreaseAllowanceResponse\"\x80\x01\n" +
	"\x14MsgDecreaseAllowance\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x18\n" +
	"\aspender\x18\x02 \x01(\tR\aspender\x12\x14\n" +
	"\x05denom\x18\x03 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount:\n" +
	"\x82\xe7\xb0*\x05owner\"\x1e\n" +
	"\x1cMsgDecreaseAllowanceResponse2\x9f\x04\n" +
	"\x03Msg\x12J\n" +
	"\bTransfer\x12\x1a.heya.erc20.v1.MsgTransfer\x1a\".heya.erc20.v1.MsgTransferResponse\x12G\n" +
	"\aApprove\x12\x19.heya.erc20.v1.MsgApprove\x1a!.heya.erc20.v1.MsgApproveResponse\x12V\n" +
	"\fTransferFrom\x12\x1e.heya.erc20.v1.MsgTransferFrom\x1a&.heya.erc20.v1.MsgTransferFromResponse\x12e\n" +
	"\x11IncreaseAllowance\x12#.heya.erc20.v1.MsgIncreaseAllowance\x1a+.heya.erc20.v1.MsgIncreaseAllowanceResponse\x12e\n" +
	"\x11DecreaseAllowance\x12#.heya.erc20.v1.MsgDecreaseAllowance\x1a+.heya.erc20.v1.MsgDecreaseAllowanceResponse\x12V\n" +
	"\fUpdateParams\x12\x1e.heya.erc20.v1.MsgUpdateParams\x1a&.heya.erc20.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B\x14Z\x12heya/x/erc20/typesb\x06proto3"

var (
	file_heya_erc20_v1_tx_proto_rawDescOnce sync.Once
	file_heya_erc20_v1_tx_proto_rawDescData []byte
)

func file_heya_erc20_v1_tx_proto_rawDescGZIP() []byte {
	file_heya_erc20_v1_tx_proto_rawDescOnce.Do(func() {
		file_heya_erc20_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heya_erc20_v1_tx_proto_rawDesc), len(file_heya_erc20_v1_tx_proto_rawDesc)))
	})
	return file_heya_erc20_v1_tx_proto_rawDescData
}

var file_heya_erc20_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_heya_erc20_v1_tx_proto_goTypes = []any{
	(*MsgTransfer)(nil),                  // 0: heya.erc20.v1.MsgTransfer
	(*MsgTransferResponse)(nil),          // 1: heya.erc20.v1.MsgTransferResponse
	(*MsgApprove)(nil),                   // 2: heya.erc20.v1.MsgApprove
	(*MsgApproveResponse)(nil),           // 3: heya.erc20.v1.MsgApproveResponse
	(*MsgTransferFrom)(nil),              // 4: heya.erc20.v1.MsgTransferFrom
	(*MsgTransferFromResponse)(nil),      // 5: heya.erc20.v1.MsgTransferFromResponse
	(*MsgUpdateParams)(nil),              // 6: heya.erc20.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),      // 7: heya.erc20.v1.MsgUpdateParamsResponse
	(*MsgIncreaseAllowance)(nil),         // 8: heya.erc20.v1.MsgIncreaseAllowance
	(*MsgIncreaseAllowanceResponse)(nil), // 9: heya.erc20.v1.MsgIncreaseAllowanceResponse
	(*MsgDecreaseAllowance)(nil),         // 10: heya.erc20.v1.MsgDecreaseAllowance
	(*MsgDecreaseAllowanceResponse)(nil), // 11: heya.erc20.v1.MsgDecreaseAllowanceResponse
}
var file_heya_erc20_v1_tx_proto_depIdxs = []int32{
	0,  // 0: heya.erc20.v1.Msg.Transfer:input_type -> heya.erc20.v1.MsgTransfer
	2,  // 1: heya.erc20.v1.Msg.Approve:input_type -> heya.erc20.v1.MsgApprove
	4,  // 2: heya.erc20.v1.Msg.TransferFrom:input_type -> heya.erc20.v1.MsgTransferFrom
	8,  // 3: heya.erc20.v1.Msg.IncreaseAllowance:input_type -> heya.erc20.v1.MsgIncreaseAllowance
	10, // 4: heya.erc20.v1.Msg.DecreaseAllowance:input_type -> heya.erc20.v1.MsgDecreaseAllowance
	6,  // 5: heya.erc20.v1.Msg.UpdateParams:input_type -> heya.erc20.v1.MsgUpdateParams
	1,  // 6: heya.erc20.v1.Msg.Transfer:output_type -> heya.erc20.v1.MsgTransferResponse
	3,  // 7: heya.erc20.v1.Msg.Approve:output_type -> heya.erc20.v1.MsgApproveResponse
	5,  // 8: heya.erc20.v1.Msg.TransferFrom:output_type -> heya.erc20.v1.MsgTransferFromResponse
	9,  // 9: heya.erc20.v1.Msg.IncreaseAllowance:output_type -> heya.erc20.v1.MsgIncreaseAllowanceResponse
	11, // 10: heya.erc20.v1.Msg.DecreaseAllowance:output_type -> heya.erc20.v1.MsgDecreaseAllowanceResponse
	7,  // 11: heya.erc20.v1.Msg.UpdateParams:output_type -> heya.erc20.v1.MsgUpdateParamsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_heya_erc20_v1_tx_proto_init() }
func file_heya_erc20_v1_tx_proto_init() {
	if File_heya_erc20_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heya_erc20_v1_tx_proto_rawDesc), len(file_heya_erc20_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heya_erc20_v1_tx_proto_goTypes,
		DependencyIndexes: file_heya_erc20_v1_tx_proto_depIdxs,
		MessageInfos:      file_heya_erc20_v1_tx_proto_msgTypes,
	}.Build()
	File_heya_erc20_v1_tx_proto = out.File
	file_heya_erc20_v1_tx_proto_goTypes = nil
	file_heya_erc20_v1_tx_proto_depIdxs = nil
}
