// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: heya/tokenfactory/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgCreateDenom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Subdenom      string                 `protobuf:"bytes,2,opt,name=subdenom,proto3" json:"subdenom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateDenom) Reset() {
	*x = MsgCreateDenom{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateDenom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateDenom) ProtoMessage() {}

func (x *MsgCreateDenom) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateDenom.ProtoReflect.Descriptor instead.
func (*MsgCreateDenom) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateDenom) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgCreateDenom) GetSubdenom() string {
	if x != nil {
		return x.Subdenom
	}
	return ""
}

type MsgCreateDenomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateDenomResponse) Reset() {
	*x = MsgCreateDenomResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateDenomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateDenomResponse) ProtoMessage() {}

func (x *MsgCreateDenomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateDenomResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateDenomResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateDenomResponse) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type MsgMint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	MintTo        string                 `protobuf:"bytes,3,opt,name=mint_to,json=mintTo,proto3" json:"mint_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMint) Reset() {
	*x = MsgMint{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMint) ProtoMessage() {}

func (x *MsgMint) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMint.ProtoReflect.Descriptor instead.
func (*MsgMint) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgMint) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgMint) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgMint) GetMintTo() string {
	if x != nil {
		return x.MintTo
	}
	return ""
}

type MsgMintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMintResponse) Reset() {
	*x = MsgMintResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintResponse) ProtoMessage() {}

func (x *MsgMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintResponse.ProtoReflect.Descriptor instead.
func (*MsgMintResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgBurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBurn) Reset() {
	*x = MsgBurn{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBurn) ProtoMessage() {}

func (x *MsgBurn) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBurn.ProtoReflect.Descriptor instead.
func (*MsgBurn) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgBurn) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgBurn) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgBurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBurnResponse) Reset() {
	*x = MsgBurnResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBurnResponse) ProtoMessage() {}

func (x *MsgBurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBurnResponse.ProtoReflect.Descriptor instead.
func (*MsgBurnResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{5}
}

type MsgChangeAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	NewAdmin      string                 `protobuf:"bytes,3,opt,name=new_admin,json=newAdmin,proto3" json:"new_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgChangeAdmin) Reset() {
	*x = MsgChangeAdmin{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgChangeAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgChangeAdmin) ProtoMessage() {}

func (x *MsgChangeAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgChangeAdmin.ProtoReflect.Descriptor instead.
func (*MsgChangeAdmin) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgChangeAdmin) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgChangeAdmin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgChangeAdmin) GetNewAdmin() string {
	if x != nil {
		return x.NewAdmin
	}
	return ""
}

type MsgChangeAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgChangeAdminResponse) Reset() {
	*x = MsgChangeAdminResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgChangeAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgChangeAdminResponse) ProtoMessage() {}

func (x *MsgChangeAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgChangeAdminResponse.ProtoReflect.Descriptor instead.
func (*MsgChangeAdminResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{7}
}

type MsgForceTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DestAddr      string                 `protobuf:"bytes,3,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	FromAddress   string                 `protobuf:"bytes,4,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgForceTransfer) Reset() {
	*x = MsgForceTransfer{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgForceTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgForceTransfer) ProtoMessage() {}

func (x *MsgForceTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgForceTransfer.ProtoReflect.Descriptor instead.
func (*MsgForceTransfer) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgForceTransfer) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgForceTransfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgForceTransfer) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *MsgForceTransfer) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

type MsgForceTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgForceTransferResponse) Reset() {
	*x = MsgForceTransferResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgForceTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgForceTransferResponse) ProtoMessage() {}

func (x *MsgForceTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgForceTransferResponse.ProtoReflect.Descriptor instead.
func (*MsgForceTransferResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{9}
}

type MsgAcceptAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         string                 `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAcceptAdmin) Reset() {
	*x = MsgAcceptAdmin{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAcceptAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAcceptAdmin) ProtoMessage() {}

func (x *MsgAcceptAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAcceptAdmin.ProtoReflect.Descriptor instead.
func (*MsgAcceptAdmin) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgAcceptAdmin) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

func (x *MsgAcceptAdmin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type MsgAcceptAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAcceptAdminResponse) Reset() {
	*x = MsgAcceptAdminResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAcceptAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAcceptAdminResponse) ProtoMessage() {}

func (x *MsgAcceptAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAcceptAdminResponse.ProtoReflect.Descriptor instead.
func (*MsgAcceptAdminResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{11}
}

type MsgUpdateParams struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Authority        string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	DenomCreationFee string                 `protobuf:"bytes,2,opt,name=denom_creation_fee,json=denomCreationFee,proto3" json:"denom_creation_fee,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{12}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetDenomCreationFee() string {
	if x != nil {
		return x.DenomCreationFee
	}
	return ""
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_tx_proto_rawDescGZIP(), []int{13}
}

var File_heya_tokenfactory_v1_tx_proto protoreflect.FileDescriptor

const file_heya_tokenfactory_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1dheya/tokenfactory/v1/tx.proto\x12\x14heya.tokenfactory.v1\x1a\x17cosmos/msg/v1/msg.proto\"Q\n" +
	"\x0eMsgCreateDenom\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\bsubdenom\x18\x02 \x01(\tR\bsubdenom:\v\x82\xe7\xb0*\x06sender\".\n" +
	"\x16MsgCreateDenomResponse\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\"_\n" +
	"\aMsgMint\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x17\n" +
	"\amint_to\x18\x03 \x01(\tR\x06mintTo:\v\x82\xe7\xb0*\x06sender\"\x11\n" +
	"\x0fMsgMintResponse\"F\n" +
	"\aMsgBurn\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount:\v\x82\xe7\xb0*\x06sender\"\x11\n" +
	"\x0fMsgBurnResponse\"h\n" +
	"\x0eMsgChangeAdmin\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\x12\x1b\n" +
	"\tnew_admin\x18\x03 \x01(\tR\bnewAdmin:\v\x82\xe7\xb0*\x06sender\"\x18\n" +
	"\x16MsgChangeAdminResponse\"\x8f\x01\n" +
	"\x10MsgForceTransfer\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1b\n" +
	"\tdest_addr\x18\x03 \x01(\tR\bdestAddr\x12!\n" +
	"\ffrom_address\x18\x04 \x01(\tR\vfromAddress:\v\x82\xe7\xb0*\x06sender\"\x1a\n" +
	"\x18MsgForceTransferResponse\"H\n" +
	"\x0eMsgAcceptAdmin\x12\x14\n" +
	"\x05admin\x18\x01 \x01(\tR\x05admin\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom:\n" +
	"\x82\xe7\xb0*\x05admin\"\x18\n" +
	"\x16MsgAcceptAdminResponse\"m\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12,\n" +
	"\x12denom_creation_fee\x18\x02 \x01(\tR\x10denomCreationFee:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\xa0\x05\n" +
	"\x03Msg\x12a\n" +
	"\vCreateDenom\x12$.heya.tokenfactory.v1.MsgCreateDenom\x1a,.heya.tokenfactory.v1.MsgCreateDenomResponse\x12L\n" +
	"\x04Mint\x12\x1d.heya.tokenfactory.v1.MsgMint\x1a%.heya.tokenfactory.v1.MsgMintResponse\x12L\n" +
	"\x04Burn\x12\x1d.heya.tokenfactory.v1.MsgBurn\x1a%.heya.tokenfactory.v1.MsgBurnResponse\x12a\n" +
	"\vChangeAdmin\x12$.heya.tokenfactory.v1.MsgChangeAdmin\x1a,.heya.tokenfactory.v1.MsgChangeAdminResponse\x12g\n" +
	"\rForceTransfer\x12&.heya.tokenfactory.v1.MsgForceTransfer\x1a..heya.tokenfactory.v1.MsgForceTransferResponse\x12a\n" +
	"\vAcceptAdmin\x12$.heya.tokenfactory.v1.MsgAcceptAdmin\x1a,.heya.tokenfactory.v1.MsgAcceptAdminResponse\x12d\n" +
	"\fUpdateParams\x12%.heya.tokenfactory.v1.MsgUpdateParams\x1a-.heya.tokenfactory.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B\x1bZ\x19heya/x/tokenfactory/typesb\x06proto3"

var (
	file_heya_tokenfactory_v1_tx_proto_rawDescOnce sync.Once
	file_heya_tokenfactory_v1_tx_proto_rawDescData []byte
)

func file_heya_tokenfactory_v1_tx_proto_rawDescGZIP() []byte {
	file_heya_tokenfactory_v1_tx_proto_rawDescOnce.Do(func() {
		file_heya_tokenfactory_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heya_tokenfactory_v1_tx_proto_rawDesc), len(file_heya_tokenfactory_v1_tx_proto_rawDesc)))
	})
	return file_heya_tokenfactory_v1_tx_proto_rawDescData
}

var file_heya_tokenfactory_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_heya_tokenfactory_v1_tx_proto_goTypes = []any{
	(*MsgCreateDenom)(nil),           // 0: heya.tokenfactory.v1.MsgCreateDenom
	(*MsgCreateDenomResponse)(nil),   // 1: heya.tokenfactory.v1.MsgCreateDenomResponse
	(*MsgMint)(nil),                  // 2: heya.tokenfactory.v1.MsgMint
	(*MsgMintResponse)(nil),          // 3: heya.tokenfactory.v1.MsgMintResponse
	(*MsgBurn)(nil),                  // 4: heya.tokenfactory.v1.MsgBurn
	(*MsgBurnResponse)(nil),          // 5: heya.tokenfactory.v1.MsgBurnResponse
	(*MsgChangeAdmin)(nil),           // 6: heya.tokenfactory.v1.MsgChangeAdmin
	(*MsgChangeAdminResponse)(nil),   // 7: heya.tokenfactory.v1.MsgChangeAdminResponse
	(*MsgForceTransfer)(nil),         // 8: heya.tokenfactory.v1.MsgForceTransfer
	(*MsgForceTransferResponse)(nil), // 9: heya.tokenfactory.v1.MsgForceTransferResponse
	(*MsgAcceptAdmin)(nil),           // 10: heya.tokenfactory.v1.MsgAcceptAdmin
	(*MsgAcceptAdminResponse)(nil),   // 11: heya.tokenfactory.v1.MsgAcceptAdminResponse
	(*MsgUpdateParams)(nil),          // 12: heya.tokenfactory.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),  // 13: heya.tokenfactory.v1.MsgUpdateParamsResponse
}
var file_heya_tokenfactory_v1_tx_proto_depIdxs = []int32{
	0,  // 0: heya.tokenfactory.v1.Msg.CreateDenom:input_type -> heya.tokenfactory.v1.MsgCreateDenom
	2,  // 1: heya.tokenfactory.v1.Msg.Mint:input_type -> heya.tokenfactory.v1.MsgMint
	4,  // 2: heya.tokenfactory.v1.Msg.Burn:input_type -> heya.tokenfactory.v1.MsgBurn
	6,  // 3: heya.tokenfactory.v1.Msg.ChangeAdmin:input_type -> heya.tokenfactory.v1.MsgChangeAdmin
	8,  // 4: heya.tokenfactory.v1.Msg.ForceTransfer:input_type -> heya.tokenfactory.v1.MsgForceTransfer
	10, // 5: heya.tokenfactory.v1.Msg.AcceptAdmin:input_type -> heya.tokenfactory.v1.MsgAcceptAdmin
	12, // 6: heya.tokenfactory.v1.Msg.UpdateParams:input_type -> heya.tokenfactory.v1.MsgUpdateParams
	1,  // 7: heya.tokenfactory.v1.Msg.CreateDenom:output_type -> heya.tokenfactory.v1.MsgCreateDenomResponse
	3,  // 8: heya.tokenfactory.v1.Msg.Mint:output_type -> heya.tokenfactory.v1.MsgMintResponse
	5,  // 9: heya.tokenfactory.v1.Msg.Burn:output_type -> heya.tokenfactory.v1.MsgBurnResponse
	7,  // 10: heya.tokenfactory.v1.Msg.ChangeAdmin:output_type -> heya.tokenfactory.v1.MsgChangeAdminResponse
	9,  // 11: heya.tokenfactory.v1.Msg.ForceTransfer:output_type -> heya.tokenfactory.v1.MsgForceTransferResponse
	11, // 12: heya.tokenfactory.v1.Msg.AcceptAdmin:output_type -> heya.tokenfactory.v1.MsgAcceptAdminResponse
	13, // 13: heya.tokenfactory.v1.Msg.UpdateParams:output_type -> heya.tokenfactory.v1.MsgUpdateParamsResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_heya_tokenfactory_v1_tx_proto_init() }
func file_heya_tokenfactory_v1_tx_proto_init() {
	if File_heya_tokenfactory_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heya_tokenfactory_v1_tx_proto_rawDesc), len(file_heya_tokenfactory_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heya_tokenfactory_v1_tx_proto_goTypes,
		DependencyIndexes: file_heya_tokenfactory_v1_tx_proto_depIdxs,
		MessageInfos:      file_heya_tokenfactory_v1_tx_proto_msgTypes,
	}.Build()
	File_heya_tokenfactory_v1_tx_proto = out.File
	file_heya_tokenfactory_v1_tx_proto_goTypes = nil
	file_heya_tokenfactory_v1_tx_proto_depIdxs = nil
}
