// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: heya/tokenfactory/v1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryDenomAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDenomAdminRequest) Reset() {
	*x = QueryDenomAdminRequest{}
	mi := &file_heya_tokenfactory_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDenomAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDenomAdminRequest) ProtoMessage() {}

func (x *QueryDenomAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDenomAdminRequest.ProtoReflect.Descriptor instead.
func (*QueryDenomAdminRequest) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryDenomAdminRequest) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type QueryDenomAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         string                 `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDenomAdminResponse) Reset() {
	*x = QueryDenomAdminResponse{}
	mi := &file_heya_tokenfactory_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDenomAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDenomAdminResponse) ProtoMessage() {}

func (x *QueryDenomAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDenomAdminResponse.ProtoReflect.Descriptor instead.
func (*QueryDenomAdminResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryDenomAdminResponse) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_heya_tokenfactory_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_query_proto_rawDescGZIP(), []int{2}
}

type QueryParamsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DenomCreationFee string                 `protobuf:"bytes,1,opt,name=denom_creation_fee,json=denomCreationFee,proto3" json:"denom_creation_fee,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_heya_tokenfactory_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heya_tokenfactory_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_heya_tokenfactory_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryParamsResponse) GetDenomCreationFee() string {
	if x != nil {
		return x.DenomCreationFee
	}
	return ""
}

var File_heya_tokenfactory_v1_query_proto protoreflect.FileDescriptor

const file_heya_tokenfactory_v1_query_proto_rawDesc = "" +
	"\n" +
	" heya/tokenfactory/v1/query.proto\x12\x14heya.tokenfactory.v1\".\n" +
	"\x16QueryDenomAdminRequest\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\"/\n" +
	"\x17QueryDenomAdminResponse\x12\x14\n" +
	"\x05admin\x18\x01 \x01(\tR\x05admin\"\x14\n" +
	"\x12QueryParamsRequest\"C\n" +
	"\x13QueryParamsResponse\x12,\n" +
	"\x12denom_creation_fee\x18\x01 \x01(\tR\x10denomCreationFee2\xd1\x01\n" +
	"\x05Query\x12i\n" +
	"\n" +
	"DenomAdmin\x12,.heya.tokenfactory.v1.QueryDenomAdminRequest\x1a-.heya.tokenfactory.v1.QueryDenomAdminResponse\x12]\n" +
	"\x06Params\x12(.heya.tokenfactory.v1.QueryParamsRequest\x1a).heya.tokenfactory.v1.QueryParamsResponseB\x1bZ\x19heya/x/tokenfactory/typesb\x06proto3"

var (
	file_heya_tokenfactory_v1_query_proto_rawDescOnce sync.Once
	file_heya_tokenfactory_v1_query_proto_rawDescData []byte
)

func file_heya_tokenfactory_v1_query_proto_rawDescGZIP() []byte {
	file_heya_tokenfactory_v1_query_proto_rawDescOnce.Do(func() {
		file_heya_tokenfactory_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_heya_tokenfactory_v1_query_proto_rawDesc), len(file_heya_tokenfactory_v1_query_proto_rawDesc)))
	})
	return file_heya_tokenfactory_v1_query_proto_rawDescData
}

var file_heya_tokenfactory_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_heya_tokenfactory_v1_query_proto_goTypes = []any{
	(*QueryDenomAdminRequest)(nil),  // 0: heya.tokenfactory.v1.QueryDenomAdminRequest
	(*QueryDenomAdminResponse)(nil), // 1: heya.tokenfactory.v1.QueryDenomAdminResponse
	(*QueryParamsRequest)(nil),      // 2: heya.tokenfactory.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),     // 3: heya.tokenfactory.v1.QueryParamsResponse
}
var file_heya_tokenfactory_v1_query_proto_depIdxs = []int32{
	0, // 0: heya.tokenfactory.v1.Query.DenomAdmin:input_type -> heya.tokenfactory.v1.QueryDenomAdminRequest
	2, // 1: heya.tokenfactory.v1.Query.Params:input_type -> heya.tokenfactory.v1.QueryParamsRequest
	1, // 2: heya.tokenfactory.v1.Query.DenomAdmin:output_type -> heya.tokenfactory.v1.QueryDenomAdminResponse
	3, // 3: heya.tokenfactory.v1.Query.Params:output_type -> heya.tokenfactory.v1.QueryParamsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heya_tokenfactory_v1_query_proto_init() }
func file_heya_tokenfactory_v1_query_proto_init() {
	if File_heya_tokenfactory_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_heya_tokenfactory_v1_query_proto_rawDesc), len(file_heya_tokenfactory_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heya_tokenfactory_v1_query_proto_goTypes,
		DependencyIndexes: file_heya_tokenfactory_v1_query_proto_depIdxs,
		MessageInfos:      file_heya_tokenfactory_v1_query_proto_msgTypes,
	}.Build()
	File_heya_tokenfactory_v1_query_proto = out.File
	file_heya_tokenfactory_v1_query_proto_goTypes = nil
	file_heya_tokenfactory_v1_query_proto_depIdxs = nil
}
